import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { Minus, Plus, ShieldCheck, Truck, ArrowLeft, Quote } from "lucide-react";
import { useState } from "react";
import { getProduct, formatPrice } from "@/lib/catalog";
import { useCart } from "@/lib/cart";
import { Button } from "@/components/ui/button";
export const Route = createFileRoute("/product/$slug")({
  loader: ({ params }) => { const product = getProduct(params.slug); if (!product) throw notFound(); return product; },
  head: ({ loaderData }) => ({ meta: [ { title: loaderData ? `${loaderData.name} | Lowyalty` : "Product not found | Lowyalty" }, { name: "description", content: loaderData?.description ?? "Browse Lowyalty print products." }, { property: "og:title", content: loaderData?.name ?? "Lowyalty product" }, { property: "og:description", content: loaderData?.description ?? "Custom print and branding." }, { property: "og:image", content: "/favicon.png" }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }, { name: "twitter:image", content: "/favicon.png" } ] }),
  component: ProductPage,
});
function ProductPage() { const product=Route.useLoaderData(); const [quantity,setQuantity]=useState(1); const {addItem}=useCart(); return <div className="site-container section-pad"><Link to="/shop" search={{q:undefined,category:undefined}} className="inline-flex items-center gap-2 text-sm font-bold text-muted-foreground hover:text-primary"><ArrowLeft size={17}/>Back to shop</Link><div className="mt-8 grid gap-10 lg:grid-cols-2"><img src={product.image} alt={product.name} width={1200} height={912} className="aspect-[4/3] w-full rounded-md object-cover object-center"/><div className="lg:pl-8"><span className="text-sm font-black uppercase text-primary">{product.category}</span><h1 className="mt-3 font-display text-4xl font-black sm:text-5xl">{product.name}</h1><p className="mt-5 text-lg leading-8 text-muted-foreground">{product.description}</p>{product.quoteOnly ? (<p className="mt-7 text-2xl font-black text-primary">Pricing on request</p>) : (<p className="mt-7 text-3xl font-black">{formatPrice(product.price)} <span className="text-sm font-medium text-muted-foreground">/ {product.unit}</span></p>)}{!product.quoteOnly && (<div className="mt-7 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Finish<select className="mt-2 h-12 w-full rounded-md border border-input bg-background px-3 font-normal"><option>Standard finish</option><option>Matt finish</option><option>Gloss finish</option></select></label><label className="text-sm font-bold">Artwork<select className="mt-2 h-12 w-full rounded-md border border-input bg-background px-3 font-normal"><option>I have print-ready artwork</option><option>I need design support</option></select></label></div>)}<div className="mt-7 flex gap-3">{product.quoteOnly ? (<Button className="flex-1" asChild><Link to="/contact"><Quote size={17}/>Request a quote</Link></Button>) : (<><div className="flex h-12 items-center border border-border"><Button variant="ghost" size="icon" aria-label="Decrease quantity" onClick={()=>setQuantity(Math.max(1,quantity-1))}><Minus size={16}/></Button><span className="w-10 text-center font-bold">{quantity}</span><Button variant="ghost" size="icon" aria-label="Increase quantity" onClick={()=>setQuantity(quantity+1)}><Plus size={16}/></Button></div><Button className="flex-1" onClick={()=>addItem(product,quantity)}>Add to cart</Button></>)}</div><div className="mt-8 grid gap-3 border-t border-border pt-6 text-sm text-muted-foreground"><span className="flex gap-3"><ShieldCheck className="text-primary" size={20}/>Artwork and quality check included</span><span className="flex gap-3"><Truck className="text-primary" size={20}/>Delivery quoted by destination and order size</span></div></div></div></div> }